-- Sophie/QDB v0 private persistence contract.
-- Apply in the target Supabase project before enabling /api/qdb-ingest.

create table if not exists public.qdb_interactions (
  interaction_id text primary key,
  case_id text not null,
  advisor_id text not null,
  occurred_at timestamptz not null,
  source_type text not null default 'advisory_notes',
  source_text text not null,
  source_ref text,
  source_sha256 text not null check (source_sha256 ~ '^[0-9a-f]{64}$'),
  n8n_execution_id text not null,
  permission_basis text not null,
  processing_status text not null default 'persisted' check (processing_status in ('persisted','ready','failed')),
  extraction_count integer not null default 0 check (extraction_count >= 0),
  last_error text,
  ingested_at timestamptz not null default now(),
  processed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.qdb_extractions (
  id bigint generated by default as identity primary key,
  interaction_id text not null references public.qdb_interactions(interaction_id) on delete cascade,
  ordinal integer not null check (ordinal > 0),
  kind text not null check (kind in ('evidence','decision','commitment','unresolved','state_change')),
  statement text not null,
  source_quote text not null,
  source_start integer not null check (source_start >= 0),
  source_end integer not null check (source_end >= source_start),
  confidence double precision not null check (confidence >= 0 and confidence <= 1),
  owner text,
  due_at timestamptz,
  created_at timestamptz not null default now(),
  unique (interaction_id, ordinal)
);

create table if not exists public.qdb_state_snapshots (
  interaction_id text primary key references public.qdb_interactions(interaction_id) on delete cascade,
  case_id text not null,
  source_sha256 text not null,
  n8n_execution_id text not null,
  state jsonb not null,
  generated_at timestamptz not null default now()
);

alter table public.qdb_interactions enable row level security;
alter table public.qdb_extractions enable row level security;
alter table public.qdb_state_snapshots enable row level security;

revoke all on public.qdb_interactions from anon, authenticated;
revoke all on public.qdb_extractions from anon, authenticated;
revoke all on public.qdb_state_snapshots from anon, authenticated;

grant select, insert, update, delete on public.qdb_interactions to service_role;
grant select, insert, update, delete on public.qdb_extractions to service_role;
grant select, insert, update, delete on public.qdb_state_snapshots to service_role;

create or replace function public.qdb_apply_extraction(
  p_interaction_id text,
  p_case_id text,
  p_source_sha256 text,
  p_n8n_execution_id text,
  p_items jsonb,
  p_state jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.qdb_interactions where interaction_id = p_interaction_id) then
    raise exception 'interaction % does not exist', p_interaction_id;
  end if;

  delete from public.qdb_extractions where interaction_id = p_interaction_id;

  insert into public.qdb_extractions (
    interaction_id, ordinal, kind, statement, source_quote, source_start, source_end,
    confidence, owner, due_at
  )
  select
    p_interaction_id,
    (item->>'ordinal')::integer,
    item->>'kind',
    item->>'statement',
    item->>'source_quote',
    (item->>'source_start')::integer,
    (item->>'source_end')::integer,
    (item->>'confidence')::double precision,
    nullif(item->>'owner', ''),
    nullif(item->>'due_at', '')::timestamptz
  from jsonb_array_elements(p_items) item;

  insert into public.qdb_state_snapshots (
    interaction_id, case_id, source_sha256, n8n_execution_id, state, generated_at
  ) values (
    p_interaction_id, p_case_id, p_source_sha256, p_n8n_execution_id, p_state, now()
  )
  on conflict (interaction_id) do update set
    case_id = excluded.case_id,
    source_sha256 = excluded.source_sha256,
    n8n_execution_id = excluded.n8n_execution_id,
    state = excluded.state,
    generated_at = excluded.generated_at;

  update public.qdb_interactions
    set processing_status = 'ready',
        extraction_count = jsonb_array_length(p_items),
        last_error = null,
        processed_at = now(),
        updated_at = now()
  where interaction_id = p_interaction_id;

  return jsonb_build_object(
    'interaction_id', p_interaction_id,
    'extraction_count', jsonb_array_length(p_items),
    'state_snapshot', true,
    'status', 'ready'
  );
end;
$$;

revoke all on function public.qdb_apply_extraction(text,text,text,text,jsonb,jsonb) from public, anon, authenticated;
grant execute on function public.qdb_apply_extraction(text,text,text,text,jsonb,jsonb) to service_role;
